version: '3.9'

services:
  erythrondb-web:
    ports:
      - '8082:8080'
      - '5432:5432'
    build:
      context: .
      dockerfile: web/Dockerfile
    volumes:
      - ${DOWNLOADS}:/www/erythrondb/project_home
      - ${LOG}:/usr/local/tomcat/logs
    environment:
      DOWNLOADS: ${DOWNLOADS}
      LOG: ${LOG}
      DB_DATA: ${DB_DATA}
     
