version: '3.3'

services:
  db:
    image: postgres:14
    container_name: erythrondb-db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_INIT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_INIT_PASSWORD}
      POSTGRES_DB: init-ignore
    volumes:
      # note - db will not initialize if DB_DATA directory already exists
      - ${DB_INIT}:/docker-entrypoint-initdb.d/init.sql.gz
      - ${DB_DATA}:/var/lib/postgresql/data

  web:
    container_name: erythrondb-web
    build:
      args:
        DB_HOST: db
        BUILD: ${BUILD}
      context: .
      dockerfile: ./web/Dockerfile-with-ARGs
      target: initialize-env
      # target: one of base, initialize-env, build-web, site-admin-config
      # leave target commented out to build entire container; or set targets to build sequentially for dev or debugging
      # 1. base - create tomcat container, do update and install dependencies
      # 2. initialize-env - fetches source from github and creates webapp.prop and gus.config and sets gusEnv to enable build
      # 3. build-web - depends on initialize-env
    depends_on:
      - db
    ports:
      - '${TOMCAT_PORT}:8080'
    volumes:
      - ${LOG}:/usr/local/tomcat/logs
    # links:
    #  - db
    environment:
      PG_HOST: 'db'

volumes:
  pg-data:
    driver: local

