version: '3.3'

services:
  db:
    container_name: database
    image: postgres:14
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_INIT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_INIT_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5 --auth-local=md5
      # POSTGRES_DB: init-ignore
    volumes:
      # note - db will not initialize if DB_DATA directory already exists
      - ${DB_INIT}:/docker-entrypoint-initdb.d/init.sql.gz
      - ${DB_DATA}:/var/lib/postgresql/data

  web:
    container_name: website
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DB_PORT: ${DB_PORT}
      # target: config
    depends_on:
      - db
    ports:
      - '${TOMCAT_PORT}:8080'
    volumes:
      - ${TOMCAT_LOG}:/usr/local/tomcat/logs
    environment:
      PG_HOST: 'db'

volumes:
  pg-data:
    driver: local

